# Production Environment Configuration
environment: production

service:
  host: "0.0.0.0"
  port: 8000
  debug: false
  reload: false
  log_level: "WARNING"
  workers: 4
  max_context_length: 10
  similarity_threshold: 0.75
  temporal_window_hours: 24

weaviate:
  url: "http://weaviate:8080"
  timeout: 30
  max_retries: 3
  batch_size: 100

openai:
  model: "gpt-4"
  max_tokens: 800
  temperature: 0.3
  timeout: 30
  max_retries: 3

embedding:
  model_name: "sentence-transformers/all-MiniLM-L6-v2"
  device: "cpu"
  batch_size: 32

redis:
  host: "redis"
  port: 6379
  db: 0
  timeout: 5
  max_connections: 10

database:
  host: "postgres"
  port: 5432
  name: "surveillance_prod"
  username: "postgres"
  pool_size: 20
  max_overflow: 40

security:
  enable_cors: false
  allowed_origins: []
  rate_limit_per_minute: 60
  algorithm: "HS256"
  access_token_expire_minutes: 15

monitoring:
  enable_metrics: true
  metrics_port: 8001
  enable_tracing: true
  health_check_interval: 30
