name: Enhanced Prompt Service Tests

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'enhanced_prompt_service/**'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'enhanced_prompt_service/**'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, 3.10, 3.11]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('enhanced_prompt_service/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      working-directory: enhanced_prompt_service
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest-cov==4.1.0
    
    - name: Lint with flake8
      working-directory: enhanced_prompt_service
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Run unit tests with coverage
      working-directory: enhanced_prompt_service
      run: |
        python -m pytest tests/ \
          --cov=llm_client \
          --cov=weaviate_client \
          --cov=conversation_manager \
          --cov-report=xml \
          --cov-report=term-missing \
          --junitxml=pytest-results.xml \
          -v
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: enhanced_prompt_service/coverage.xml
        flags: enhanced_prompt_service
        name: codecov-umbrella
        fail_ci_if_error: false
    
    - name: Upload test results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: pytest-results-${{ matrix.python-version }}
        path: enhanced_prompt_service/pytest-results.xml
    
    - name: Comment coverage on PR
      if: github.event_name == 'pull_request'
      uses: py-cov-action/python-coverage-comment-action@v3
      with:
        GITHUB_TOKEN: ${{ github.token }}
        MINIMUM_GREEN: 80
        MINIMUM_ORANGE: 60
